switch to dedicated consumption plan
microsoft/azure-spring-apps-training pull request #175
Opened 2023-09-26 11:58 UTC by SandraAhlgrimm

I also updated the tracking links to the latest format

2023-09-26 19:10 UTC, mkheck requested changes
Lines 47, 52, and 60 in 01-create.../README.md have an extraneous "env" in the command:

Line 47: --name $AZ_SPRING_APPS_NAME env \

Should be:

--name $AZ_SPRING_APPS_NAME \

Same for lines 52 & 60.

2023-09-26 19:22 UTC, SandraAhlgrimm commented
> Lines 47, 52, and 60 in 01-create.../README.md have an extraneous "env" in the command:
> 
> Line 47: --name $AZ_SPRING_APPS_NAME env \
> 
> Should be:
> 
> --name $AZ_SPRING_APPS_NAME \
> 
> Same for lines 52 & 60.

Yeah it’s the name for the container environment, that’s why I used a concat string with the spring apps instance name here

2023-09-26 19:25 UTC, mkheck commented
> > Lines 47, 52, and 60 in 01-create.../README.md have an extraneous "env" in the command:
> > Line 47: --name $AZ_SPRING_APPS_NAME env \
> > Should be:
> > --name $AZ_SPRING_APPS_NAME \
> > Same for lines 52 & 60.
> 
> Yeah it’s the name for the container environment, that’s why I used a concat string with the spring apps instance name here

If that's the case, there shouldn't be a space between the $vbl and the 'env', correct?

Should be something like $AZ_SPRING_APPS_NAME'env' or $AZ_SPRING_APPS_NAME'-env', yes?

2023-09-26 19:27 UTC, SandraAhlgrimm commented
> > > Lines 47, 52, and 60 in 01-create.../README.md have an extraneous "env" in the command:
> > > Line 47: --name $AZ_SPRING_APPS_NAME env 
> > > Should be:
> > > --name $AZ_SPRING_APPS_NAME 
> > > Same for lines 52 & 60.
> > 
> > 
> > Yeah it’s the name for the container environment, that’s why I used a concat string with the spring apps instance name here
> 
> If that's the case, there shouldn't be a space between the $vbl and the 'env', correct?
> 
> Should be something like $AZ_SPRING_APPS_NAME'env' or $AZ_SPRING_APPS_NAME'-env', yes?

Or should we export a new variable for this? I would still want the variable name to be generated as I see no benefit for the user to specify a specific name here.

2023-09-26 19:31 UTC, mkheck commented
> > > > Lines 47, 52, and 60 in 01-create.../README.md have an extraneous "env" in the command:
> > > > Line 47: --name $AZ_SPRING_APPS_NAME env
> > > > Should be:
> > > > --name $AZ_SPRING_APPS_NAME
> > > > Same for lines 52 & 60.
> > > 
> > > 
> > > Yeah it’s the name for the container environment, that’s why I used a concat string with the spring apps instance name here
> > 
> > 
> > If that's the case, there shouldn't be a space between the $vbl and the 'env', correct?
> > Should be something like $AZ_SPRING_APPS_NAME'env' or $AZ_SPRING_APPS_NAME'-env', yes?
> 
> Or should we export a new variable for this? I would still want the variable name to be generated as I see no benefit for the user to specify a specific name here.

I would _greatly_ prefer to export a purpose-specific variable for this...but as long as we're consistent, I would be happy. Let me test something and place an updated suggestion here shortly.

2023-09-26 19:50 UTC, mkheck commented
Suggestion:

Add another env var similar to the following to the initial variable config:

export AZ_CONTAINER_APP_ENV=$AZ_SPRING_APPS_NAME'-container'

Then replace the lines called out above with:

--name $AZ_CONTAINER_APP_ENV

as applicable.

Seems the cleanest way forward, and I've confirmed it completes successfully.

2023-09-27 09:01 UTC, SandraAhlgrimm commented on 01-create-an-azure-spring-cloud-instance/README.md
> +
`export AZ_CONTAINER_APP_ENV=$AZ_SPRING_APPS_NAME'-container'`

2023-09-27 18:15 UTC, mkheck approved these changes

2023-09-27 18:15 UTC, merged